name: Release to NuGet

on:
  workflow_dispatch:
  release:
    types: [published]
    tags: 
      -  '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Application Version HotwiredDotNet.Core
      id: version
      uses: paulhatch/semantic-version@v5.1.0
      with:
        change_path: "HotwiredDotNet.Core"
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --skip-duplicate --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
